### PR TITLE
Update sphinx configuration

### PR DESCRIPTION
**Pull request by bwohlberg**
Update sphinx configuration,

### CODE REVIEW

**Comment by gbuzzard** [comment]
I added a script to build the conda environment to make testing and installation easier.  
When I tried to build the docs, I got an error:  

Theme error:
An error happened in rendering the page _autosummary/demo.
Reason: UndefinedError("'style' is undefined")
make: *** [html] Error 2

**Review by gbuzzard — CHANGES_REQUESTED** [review]
I added a script to build the conda environment to make testing and installation easier. When I tried to build the docs, I got an error:
Theme error: An error happened in rendering the page _autosummary/demo. Reason: UndefinedError("'style' is undefined") make: *** [html] Error

**Comment by bwohlberg** [comment]
The docs build errors was due to the pinning of the `sphinx_rtd_theme` package version.

**Review by gbuzzard — CHANGES_REQUESTED** [review]
In clean_install_all.sh on a mac, the ROOTPATH isn't set correctly.  When I do
ROOTPATH=$(realpath $(dirname $0)/..)
echo $ROOTPATH
I get 
/
I made a suggested change in line 5 that works for me, but please verify.  I also added double quotes later to allow for spaces in ROOTPATH.  
I wasn't able to test at home because I have an M2 chip and I get an error when trying to load the precompiled files for bm3d.  
Is there any chance of getting a jax version of bm3d?

**Comment by bwohlberg** [comment]
The purpose of the line
```bash
ROOTPATH=$(realpath $(dirname $0)/..)
```
was to make the functioning of the script independent of the working directory from which it's called. It works for me under both Ubuntu and OSX with bash shell. Perhaps you're using zsh? What was the error?

**Comment by gbuzzard** [comment]
Oddly enough it worked on zsh on my office mac.  My laptop at home is an M3 - I think it was running bash, but I'll have to check when I get home.

Greg
________________________________

**Review by gbuzzard — APPROVED** [review]

**Pull request merged**
